---
# Playbook for installing and configuring the base systems of the rasberry pis
# - hosts: all
#   strategy: free
#   remote_user: root
#   roles:
#      - pulseaudio

# - hosts: localhost
#   strategy: free
#   become: yes
#   remote_user: root
#   roles:
#      - rsyslog-server

- hosts: bigpi4
  strategy: free
  become: yes
  remote_user: pi
  roles:
  - baseline 
  - build-node-clang
  - build-node-perf-flamegraph
  - build-node-godot
  - build-node-documentation-tools

