---

  - name: Install godot dependencies
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - scons
        - libx11-dev
        - libxcursor-dev
        - libxinerama-dev
        - libgl1-mesa-dev
        - libglu-dev
        - libasound2-dev
        - libpulse-dev
        - libfreetype6-dev
        - libudev-dev
        - libxi-dev
        - libxrandr-dev
        - yasm

 # - name: Git clone Godot source
 #   git:
 #       repo: https://github.com/godotengine/godot.git
 #       version: 3.1
 #       recursive: yes
 #       dest: /usr/src/godot
   
 #  - name: Compile godot
 #    shell:
 #      cmd: |
 #         cd /usr/src/godot/
 #         scons platform=x11 target=debug tools=yes use_llvm=yes CCFLAGS="-g -ggdb -fno-omit-frame-pointer -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -mlittle-endian -munaligned-access" -j 4





